version: '3'
services:
    api:
        user: 1000:1000
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
        ports:
            - 3000:3000
        environment:
            NODE_ENV: development

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 123456

    adminer:
        image: adminer
        ports:
            - 8080:8080
