version: '3'
services:
    api:
        user: 1000:1000
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
        ports:
            - 3000:3000
        environment:
            NODE_ENV: development

    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: 123456
        volumes:
            - ./db_init:/docker-entrypoint-initdb.d/

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'michel@calheiros.dev'
            PGADMIN_DEFAULT_PASSWORD: '123456'
        logging:
            driver: none
        ports:
            - 8080:80
